ciTemplate: maven
appName: "App Hello World"
properties: "properties([ \
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '2', numToKeepStr: '2')), \
    parameters([ \
      booleanParam('bool1'), \
      booleanParam('bool2') \
    ]), \
])"
environment:
  - "EXAMPLE_KEY1 = 'THIS IS AN EXAMPLE VALUE1 FROM CI YAML'"
  - "EXAMPLE_KEY2 = 'THIS IS AN EXAMPLE VALUE2 FROM CI YAML'"
build:
  environment:
    - "MAVEN_OPTS='MYMAVEN_OPTS'"
  steps:
    - "mvn clean install"
    - "mvn test -Dmytest"
kaniko:
  dockerHost: https://nexus3
  credentialID: docker-credentials-id
qs:
  sonar:
    enabled: true
    host: https://sonar.host
    credentialID: sonar-credentials-id
  checkmarx:
    enabled: true
    host: https://checkmarx.host
    credentialID: checkmarx-credentials-id
deploy:
  type: gke
  cluster: local
  image: nexus.image.url



